repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: invoke-linting
        name: invoke-linting
        entry: invoke linting
        language: system
        pass_filenames: false
    -   id: invoke-typecheck
        name: invoke-typecheck
        entry: invoke typecheck
        language: system
        pass_filenames: false
